# Generated by Django 3.2.7 on 2021-11-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Category', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('sex', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sexbyproduct')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
