# Generated by Django 3.2.7 on 2021-11-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211122_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SexByProduct',
            new_name='Sex',
        ),
    ]
