# Generated by Django 3.2.7 on 2021-11-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_sexbyproduct_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='Category',
            new_name='category',
        ),
    ]
