# Generated by Django 3.2.7 on 2021-11-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_category_subcategory_category'),
        ('productorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
