# Generated by Django 3.2.7 on 2021-12-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productorder', '0002_auto_20211124_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='Customer',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productorder.customer'),
        ),
    ]
